[theme]
primaryColor = "#6F8F73"
backgroundColor = "#171817"
secondaryBackgroundColor = "#20211F"
textColor = "#E8E9E2"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
